# Generated by Django 5.0.1 on 2024-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_category_name_lang_menu_item_describtion_lang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
