# Generated by Django 5.0.1 on 2024-01-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_order_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='ordered_items', to='restaurant.menu_item'),
        ),
        migrations.DeleteModel(
            name='ordered_item',
        ),
    ]
