# Generated by Django 5.0.1 on 2024-01-08 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_order_items_delete_ordered_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderd_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item_in_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu_item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='restaurant.order')),
            ],
        ),
    ]
