# Generated by Django 5.0.1 on 2024-01-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_orderd_item_ordered_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordered_item',
            old_name='item_in_menu',
            new_name='menu_item',
        ),
    ]
