# Generated by Django 5.0.1 on 2024-01-10 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='for_how_long',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
